itens_classificados = [
    ("492 - granola (KG)", "📦 Outros ou diversos"),
    ("597 - biscoito(CX)", "📦 Outros ou diversos"),
    ("499 - açai(KG)", "📦 Outros ou diversos"),
    ("496 - achocolatado (KG)", "📦 Outros ou diversos"),
    ("495 - leite em po (KG)", "🧀 Laticínios e Frios"),
    ("285 - presunto fatiado (KG)", "🧀 Laticínios e Frios"),
    # ("285-presunto-fatiado-(KG)", "🧀 Laticínios e Frios"),
    ("286 - peito peru (KG)", "🧀 Laticínios e Frios"),
    ("287 - copa (KG)", "🧀 Laticínios e Frios"),
    ("288 - salame (KG)", "🧀 Laticínios e Frios"),
    ("574 - petit gateau (UN)", "🍬 Doces e Sobremesas"),
    ("575 - calda de sorvete (KG)", "🍬 Doces e Sobremesas"),
    ("603 - geleia de frutas vermelhas (KG)", "🍬 Doces e Sobremesas"),
    ("745 - mini cheesecake (CX)", "🍬 Doces e Sobremesas"),
    ("8 - Agua s/gas (UN)", "🥤 Bebidas"),
    ("12 - Agua c/gas (UN)", "🥤 Bebidas"),
    ("13 - agua tonica lata (UN)", "🥤 Bebidas"),
    ("15 - agua tonica zero lata (UN)", "🥤 Bebidas"),
    ("16 - coca cola lata (UN)", "🥤 Bebidas"),
    ("17 - coca zero lata (UN)", "🥤 Bebidas"),
    ("454 - pimenta paprica doce (KG)", "🧂 Temperos e Condimentos"),
    ("455 - pimenta paprica defumada (KG)", "🧂 Temperos e Condimentos"),
    ("456 - pimenta paprica picante (KG)", "🧂 Temperos e Condimentos"),
    ("461 - pimenta calabresa (KG)", "🧂 Temperos e Condimentos"),
    ("341 - hortela (UN)", "🥦 Hortifrúti"),
    ("342 - cenoura (KG)", "🥦 Hortifrúti"),
    ("343 - beterraba (UN)", "🥦 Hortifrúti"),
    ("652 - cobertura morango (KG)", "🥦 Hortifrúti"),
    ("302 - linguiça toscana frango (KG)", "🥩 Proteínas"),
    ("359 - carne de siri  (KG)", "🥩 Proteínas"),
    ("361 - marisco (KG)", "🥩 Proteínas"),
    ("362 - ostra (UN)", "🥩 Proteínas"),
    ("364 - camarao rosa (KG)", "🥩 Proteínas"),
    ("365 - camarao cinza (KG)", "🥩 Proteínas"),
    ("366 - lula (KG)", "🥩 Proteínas"),
    ("335 - ovos  (UN)", "🥩 Proteínas"),
    ("294 - pao mini ciabata (KG)", "🍞 Padaria e Massas"),
    ("295 - pao ciabata (KG)", "🍞 Padaria e Massas"),
    ("297 - pao baguete 250g (KG)", "🍞 Padaria e Massas"),
    ("488 - feijao branco (KG)", "🥫 Grãos e Secos"),
    ("489 - feijao carioca (KG)", "🥫 Grãos e Secos"),
    ("490 - linhaça dourada (KG)", "🥫 Grãos e Secos"),
    ("826 - saco de lixo  (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("827 - detergente (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("861 - taça borone  (UN)", "🍽️ Descartáveis e utensílios"),
    ("711 - guardanapo embalado (CX)", "🍽️ Descartáveis e utensílios"),
    ("602 - bolacha maria/maizena(KG)", "📦 Outros ou diversos"),
    ("651 - cobertura chocolate (KG)", "🍞 Padaria e Massas"),
    ("336 - salvia (KG)", "🧂 Temperos e Condimentos"),
    ("337 - manjericao (KG)", "📦 Outros ou diversos"),
    ("338 - manjericao (KG)", "📦 Outros ou diversos"),
    ("339 - tomilho (KG)", "🥦 Hortifrúti"),
    ("340 - louro (KG)", "📦 Outros ou diversos"),
    ("344 - berinjela (KG)", "📦 Outros ou diversos"),
    ("509 - AIOLI (KG)", "📦 Outros ou diversos"),
    ("512 - salsinha verde (KG)", "🧂 Temperos e Condimentos"),
    ("520 - carne moida (KG)", "🥩 Proteínas"),
    ("524 - peixe file (vilmar) (KG)", "🥩 Proteínas"),
    ("569 - oleo algodao  balde (UN)", "📦 Outros ou diversos"),
    ("697 - ovos de codorna (UN)", "📦 Outros ou diversos"),
    ("781 - abacate (KG)", "📦 Outros ou diversos"),
    ("824 - peixe inteiro (vilmar) (KG)", "🥩 Proteínas"),
    ("289 - presunto parma (KG)", "🧀 Laticínios e Frios"),
    ("474 - salgadinho doritos (KG)", "🧂 Temperos e Condimentos"),
    ("476 - lombo canadense (KG)", "🥩 Proteínas"),
    ("481 - pao italiano (KG)", "🍞 Padaria e Massas"),
    ("482 - milho (KG)", "📦 Outros ou diversos"),
    ("484 - pao de queijo (KG)", "🧀 Laticínios e Frios"),
    ("493 - fermento quimico (KG)", "📦 Outros ou diversos"),
    ("494 - fermento biologico seco (KG)", "📦 Outros ou diversos"),
    ("505 - geleia de pimenta (KG)", "🧂 Temperos e Condimentos"),
    ("513 - cebolinha verde (KG)", "📦 Outros ou diversos"),
    ("514 - papel alumiun (UN)", "📦 Outros ou diversos"),
    ("521 - batata frita  (KG)", "🥦 Hortifrúti"),
    ("534 - requeijao catupiry(KG)", "🧀 Laticínios e Frios"),
    ("622 - pao australiano (KG)", "🍞 Padaria e Massas"),
    ("623 - linguiça calabresa (KG)", "🥩 Proteínas"),
    ("624 - linguiça paio (KG)", "🥩 Proteínas"),
    ("690 - pao portugues (KG)", "🍞 Padaria e Massas"),
    ("691 - pao fazenda (KG)", "🍞 Padaria e Massas"),
    ("692 - pao de queijo com parmesao (KG)", "🧀 Laticínios e Frios"),
    ("693 - massa folhada (UN)", "🍞 Padaria e Massas"),
    ("725 - ostra (UN)", "🥩 Proteínas"),
    ("779 - pao baguete 100g (KG)", "🍞 Padaria e Massas"),
    ("780 - pao baguete 125g (KG)", "🍞 Padaria e Massas"),
    ("783 - cafe soluvel (KG)", "📦 Outros ou diversos"),
    ("786 - pao de queijo doce (KG)", "🧀 Laticínios e Frios"),
    ("787 - pao de queijo rech catupiry (KG)", "🧀 Laticínios e Frios"),
    ("817 - linguiça toscana(KG)", "🥩 Proteínas"),
    ("822 - camarao argentino (KG)", "🥩 Proteínas"),
    ("868 - camarao vennamei  VG (KG)", "🥩 Proteínas"),
    ("870 - pao mini couvert (KG)", "🥦 Hortifrúti"),
    ("933 - papel toalha (UN)", "📦 Outros ou diversos"),
    ("317 - cebola branca (KG)", "🥦 Hortifrúti"),
    ("318 - cebola roxa (KG)", "🥦 Hortifrúti"),
    ("319 - alho  (KG)", "🥦 Hortifrúti"),
    ("320 - alho poro (UN)", "🥦 Hortifrúti"),
    ("321 - tomate salada (KG)", "🥦 Hortifrúti"),
    ("322 - tomate cereja (KG)", "🥦 Hortifrúti"),
    ("323 - tomate molho (KG)", "🥦 Hortifrúti"),
    ("325 - pimentao amarelo (KG)", "🥦 Hortifrúti"),
    ("326 - pimentao verde (KG)", "🥦 Hortifrúti"),
    ("327 - pimentao vermelho (KG)", "🥦 Hortifrúti"),
    ("328 - rucula (KG)", "🥦 Hortifrúti"),
    ("329 - alface americana (KG)", "🥦 Hortifrúti"),
    ("330 - alface roxa (KG)", "🥦 Hortifrúti"),
    ("331 - acelga (UN)", "📦 Outros ou diversos"),
    ("332 - pepino japones  (KG)", "🥦 Hortifrúti"),
    ("333 - repolho branco  (KG)", "📦 Outros ou diversos"),
    ("334 - repolho roxo (KG)", "📦 Outros ou diversos"),
    ("345 - abobrinha (KG)", "📦 Outros ou diversos"),
    ("346 - couve-flor (KG)", "🥦 Hortifrúti"),
    ("347 - couve manteiga (UN)", "🧀 Laticínios e Frios"),
    ("348 - brocolis  (KG)", "🥦 Hortifrúti"),
    ("349 - pimenta dedo de moca (KG)", "🧂 Temperos e Condimentos"),
    ("350 - batata salsa baroa (KG)", "🥦 Hortifrúti"),
    ("351 - batata asterix (KG)", "🥦 Hortifrúti"),
    ("352 - fruta banana da terra (KG)", "🥦 Hortifrúti"),
    ("353 - fruta banana caturra (KG)", "🥦 Hortifrúti"),
    ("354 - fruta mamao papaia (KG)", "🥦 Hortifrúti"),
    ("355 - fruta mamao formosa (KG)", "🥦 Hortifrúti"),
    ("356 - fruta melancia (KG)", "🥦 Hortifrúti"),
    ("357 - fruta melao (KG)", "📦 Outros ou diversos"),
    ("358 - fruta maça (KG)", "📦 Outros ou diversos"),
    ("477 - fruta manga (KG)", "🥦 Hortifrúti"),
    ("483 - palmito (KG)", "📦 Outros ou diversos"),
    ("485 - champignon (KG)", "📦 Outros ou diversos"),
    ("527 - molho pesto (KG)", "🧂 Temperos e Condimentos"),
    ("541 - molho alcaparas e mel  (KG)", "🧂 Temperos e Condimentos"),
    ("544 - molho caeser (KG)", "🧂 Temperos e Condimentos"),
    ("545 - crotons (KG)", "📦 Outros ou diversos"),
    ("619 - agriao (KG)", "🥦 Hortifrúti"),
    ("637 - cebola miuda conserva (KG)", "🥦 Hortifrúti"),
    ("639 - alecrim  (UN)", "🥦 Hortifrúti"),
    ("642 - fruta banana branca (KG)", "🥦 Hortifrúti"),
    ("664 - sache vinagre (UN)", "🧂 Temperos e Condimentos"),
    ("687 - alface crespa (KG)", "🥦 Hortifrúti"),
    ("695 - vagem (KG)", "🥦 Hortifrúti"),
    ("775 - feijao fradinho (KG)", "🥩 Proteínas"),
    ("859 - linhaça marron (KG)", "🥫 Grãos e Secos"),
    ("931 - pepino em conserva (KG)", "🥦 Hortifrúti"),
    ("272 - manteiga(KG)", "🧀 Laticínios e Frios"),
    ("273 - creme de leite nata 45%(KG)", "🧀 Laticínios e Frios"),
    ("291 - pao mini sovadinho (KG)", "🍞 Padaria e Massas"),
    ("292 - pao mini frances (KG)", "🍞 Padaria e Massas"),
    ("293 - pao fatiado tradicional (UN)", "🍞 Padaria e Massas"),
    ("480 - pao fatiado integral (UN)", "🍞 Padaria e Massas"),
    ("530 - molho mostarda iogurte (KG)", "🧀 Laticínios e Frios"),
    ("749 - pao fatiado batata doce (UN)", "🥦 Hortifrúti"),
    ("750 - pao fatiado caseiro (UN)", "🍞 Padaria e Massas"),
    ("18 - fanta laranja lata (UN)", "🥦 Hortifrúti"),
    ("19 - guarana lata (UN)", "🥤 Bebidas"),
    ("20 - guarana zero lata (UN)", "🥤 Bebidas"),
    ("21 - sprite lata (UN)", "🥤 Bebidas"),
    ("22 - schweppers citrus lata (UN)", "📦 Outros ou diversos"),
    ("26 - energetico red bull lata (UN)", "🥤 Bebidas"),
    ("27 - energetico red bull tropical lata (UN)", "🥤 Bebidas"),
    ("192 - coco gelado  (UN)", "📦 Outros ou diversos"),
    ("784 - guarana pet (UN)", "🥤 Bebidas"),
    ("913 - energetico red bull sugar free (UN)", "🥤 Bebidas"),
    ("153 - picole nestle moca cone (UN)", "🍬 Doces e Sobremesas"),
    ("154 - picole nestle prestigio (UN)", "🍬 Doces e Sobremesas"),
    ("155 - picole nestle classico ao leite (UN)", "🧀 Laticínios e Frios"),
    ("156 - picole nestle  baton (UN)", "🍬 Doces e Sobremesas"),
    ("157 - picole nestle  chambinho morango (UN)", "🥦 Hortifrúti"),
    ("158 - picole nestle diamante negro  (UN)", "🍬 Doces e Sobremesas"),
    ("159 - picole nestle fine dentadura  (UN)", "🍬 Doces e Sobremesas"),
    ("160 - picole nestle fine torcao (UN)", "🍬 Doces e Sobremesas"),
    ("161 - picole nestle fine tubes morango  (UN)", "🥦 Hortifrúti"),
    ("162 - picole nestle kit kat (UN)", "🍬 Doces e Sobremesas"),
    ("163 - picole nestle la fruta coco (UN)", "🍬 Doces e Sobremesas"),
    ("164 - picole nestle la fruta limao  (UN)", "🍬 Doces e Sobremesas"),
    ("165 - picole nestle la fruta morango (UN)", "🥦 Hortifrúti"),
    ("166 - picole nestle la fruta uva (UN)", "🥦 Hortifrúti"),
    ("167 - picole nestle  laka (UN)", "🍬 Doces e Sobremesas"),
    ("168 - picole nestle  laka oreo  (UN)", "🍬 Doces e Sobremesas"),
    ("169 - picole nestle  mega alfajor (UN)", "🍬 Doces e Sobremesas"),
    ("170 - picole nestle  mega cheesecake (UN)", "🍬 Doces e Sobremesas"),
    ("171 - picole nestle  mega classico (UN)", "🍬 Doces e Sobremesas"),
    ("172 - picole nestle  mega tres chocolates (UN)", "🍬 Doces e Sobremesas"),
    ("173 - picole nestle moca brigadeiro (UN)", "🍬 Doces e Sobremesas"),
    ("174 - picole nestle sonho de valsa (UN)", "🍬 Doces e Sobremesas"),
    ("175 - picole nestle oreo  (UN)", "🍬 Doces e Sobremesas"),
    ("176 - picole nestle oreo cone  (UN)", "🍬 Doces e Sobremesas"),
    ("177 - picole nestle sanduiche oreo (UN)", "🍬 Doces e Sobremesas"),
    ("568 - sorvete nestle pote  creme (LT)", "🧀 Laticínios e Frios"),
    ("730 - picole nestle fine tubes tutti  frutti (UN)", "🍬 Doces e Sobremesas"),
    ("731 - picole nestle  mega amendoas (UN)", "🥫 Grãos e Secos"),
    ("732 - picole nestle garoto bombom (UN)", "🍬 Doces e Sobremesas"),
    ("733 - picole nestle kitkat (UN)", "🍬 Doces e Sobremesas"),
    ("734 - picole nestle cone kitkat (UN)", "🍬 Doces e Sobremesas"),
    ("752 - picole nestle mega trufa branco (UN)", "🍬 Doces e Sobremesas"),
    ("899 - picole pote oreo bites (UN)", "🍬 Doces e Sobremesas"),
    ("909 - picole nestle la fruta maracuja (UN)", "🍬 Doces e Sobremesas"),
    ("910 - picole nestle  mega pistache (UN)", "🍬 Doces e Sobremesas"),
    ("911 - picole nestle crocante (UN)", "🍬 Doces e Sobremesas"),
    ("119 - vinho tinto luigi bosca cabernet sauviginon (UN)", "🥤 Bebidas"),
    ("120 - vinho tinto terranoble carmenere (UN)", "🥤 Bebidas"),
    ("121 - vinho tinto claude val paul mas  (UN)", "🥤 Bebidas"),
    ("122 - vinho tinto intis cabernet sauviginon (UN)", "🥤 Bebidas"),
    ("123 - vinho tinto la linda malbec (UN)", "🥤 Bebidas"),
    ("124 - vinho tinto marques de montemor quinta da pansel (UN)", "🥤 Bebidas"),
    ("125 - vinho tinto olapo melot los lirios (UN)", "🥤 Bebidas"),
    ("126 - vinho tinto rey de copas tempranillo (UN)", "🥤 Bebidas"),
    ("127 - vinho tinto villa cardeto sangiovese (UN)", "🥤 Bebidas"),
    ("128 - vinho tinto terranoble cabernet sauvignon 375ml (UN)", "🥤 Bebidas"),
    ("728 - vinho tinto alta yari malbec (UN)", "🥤 Bebidas"),
    ("729 - vinho tinto sutil reserva carmenere  (UN)", "🥤 Bebidas"),
    ("821 - vinho tinto intis malbec (UN)", "🥤 Bebidas"),
    ("890 - vinho tinto uko estate pinot noir (UN)", "🥤 Bebidas"),
    ("891 - vinho tinto uko estate cabernet sauvignon (UN)", "🥤 Bebidas"),
    ("892 - vinho tinto mister uko malbec (UN)", "🥤 Bebidas"),
    ("893 - vinho tinto conclave nocturno cabernet franc (UN)", "🥤 Bebidas"),
    ("914 - vinho tinto conclave nocturno malbec (UN)", "🥤 Bebidas"),
    ("107 - vinho branco amalaya torrontes riesling (UN)", "🥤 Bebidas"),
    ("108 - vinho branco fausto pizzato chardonnay (UN)", "🥤 Bebidas"),
    ("110 - vinho branco intis sauvignon blanc (UN)", "🥤 Bebidas"),
    ("111 - vinho branco la linda chardonnay (UN)", "🥤 Bebidas"),
    ("112 - vinho branco marques de toledo (UN)", "🥤 Bebidas"),
    ("113 - vinho branco muros antigos  (UN)", "🥤 Bebidas"),
    ("114 - vinho branco  olapo chardonnay (UN)", "🥤 Bebidas"),
    ("115 - vinho branco claude val paul mas gewustraminer (UN)", "🥤 Bebidas"),
    ("116 - vinho branco thera sauvignon blanc (UN)", "🥤 Bebidas"),
    ("117 - vinho branco vila cardeto pinot grigio (UN)", "🥤 Bebidas"),
    ("118 - vinho branco terranoble chardonnay 375ml (UN)", "🥤 Bebidas"),
    ("884 - vinho branco uko estate cherdonnay  (UN)", "🥤 Bebidas"),
    ("885 - vinho branco uko estate sauvignon blanc (UN)", "🥤 Bebidas"),
    ("886 - vinho branco uko estate dulce (UN)", "🥤 Bebidas"),
    ("887 - vinho branco fumata bianca sauvignon (UN)", "🥤 Bebidas"),
    ("129 - vinho rose claude val  paul mas (UN)", "🥤 Bebidas"),
    ("130 - vinho rose las moras shyraz (UN)", "🥤 Bebidas"),
    ("131 - vinho rose thera rose  (UN)", "🥤 Bebidas"),
    ("888 - vinho uko estate malbec rose (UN)", "🥤 Bebidas"),
    ("889 - vinho conclave reserva rose (UN)", "🥤 Bebidas"),
    ("102 - espumante bossa dem sec n2 (UN)", "🥤 Bebidas"),
    ("103 - espumante bossa moscatel (UN)", "🥤 Bebidas"),
    ("104 - espumante bossa brut (UN)", "🥤 Bebidas"),
    ("105 - espumante fausto demi sec (UN)", "🥤 Bebidas"),
    ("106 - espumante la linda extra brut (UN)", "🥤 Bebidas"),
    ("894 - espumante cambiado dulce natural (UN)", "🥤 Bebidas"),
    ("895 - espumante allegra rose extra brut (UN)", "🥤 Bebidas"),
    ("912 - espumante chandon demi sec (UN)", "🥤 Bebidas"),
    ("929 - espumante chandon brut (UN)", "🥤 Bebidas"),
    ("28 - cerveja original 600ml (UN)", "🥤 Bebidas"),
    ("29 - cerveja heineken long neck (UN)", "🥤 Bebidas"),
    ("30 - cerveja corona long neck (UN)", "🥤 Bebidas"),
    ("31 - balde/heineken long neck 10und (UN)", "📦 Outros ou diversos"),
    ("32 - balde/corona long neck 10und (UN)", "📦 Outros ou diversos"),
    ("33 - cerveja heineken long neck  zero  (UN)", "🥤 Bebidas"),
    ("773 - chop  schornstein (UN)", "📦 Outros ou diversos"),
    ("774 - cerveja heineken 600ml (UN)", "🥤 Bebidas"),
    ("132 - garrafa aperol (UN)", "🥤 Bebidas"),
    ("133 - garrafa cachaca  (UN)", "📦 Outros ou diversos"),
    ("134 - garrafa whisk jack daniels (UN)", "🥤 Bebidas"),
    ("135 - garrafa  martine rosso (UN)", "📦 Outros ou diversos"),
    ("136 - garrafa  jagermaister (UN)", "🥤 Bebidas"),
    ("137 - garrafa  gin tanqueray (UN)", "🥤 Bebidas"),
    ("138 - garrafa tequila ouro  (UN)", "📦 Outros ou diversos"),
    ("139 - garrafa tequila prata (UN)", "📦 Outros ou diversos"),
    ("140 - garrafa vodka absolut (UN)", "🥤 Bebidas"),
    ("141 - garrafa vodka smirnoff (UN)", "🥤 Bebidas"),
    ("142 - garrafa vodka ciroc (UN)", "🥤 Bebidas"),
    ("143 - garrafa whisk ballantinnes 12 anos (UN)", "🥤 Bebidas"),
    ("144 - garrafa whisk black label12 anos (UN)", "🥤 Bebidas"),
    ("145 - garrafa whisk red label (UN)", "🥤 Bebidas"),
    ("147 - combo smirnoff (UN)", "📦 Outros ou diversos"),
    ("149 - garrafa campari  (UN)", "🥤 Bebidas"),
    ("150 - combo whisk jack daniels (UN)", "🥤 Bebidas"),
    ("378 - garrafa bacardi carta blanca (UN)", "📦 Outros ou diversos"),
    ("385 - garrafa  gin gordons (UN)", "🥤 Bebidas"),
    ("607 - garrafa amarula (UN)", "🥤 Bebidas"),
    ("608 -  garrafa licor 43 (UN)", "🥤 Bebidas"),
    ("720 - garrafa whisk chivas 12 anos (UN)", "🥤 Bebidas"),
    ("777 - garrafa  gin bombay (UN)", "🥤 Bebidas"),
    ("778 - garrafa rum montila branca (UN)", "🥤 Bebidas"),
    ("71 - dose amarula  (UN)", "🥤 Bebidas"),
    ("73 - dose bacardi (UN)", "📦 Outros ou diversos"),
    ("74 - dose campari (UN)", "🥤 Bebidas"),
    ("75 - dose cachaça (UN)", "📦 Outros ou diversos"),
    ("76 - dose gin tanqueray (UN)", "🥤 Bebidas"),
    ("77 - dose jack daniels (UN)", "📦 Outros ou diversos"),
    ("78 - dose jagermeister (UN)", "📦 Outros ou diversos"),
    ("79 - dose licor 43 (UN)", "🥤 Bebidas"),
    ("80 - dose steinhaeguer  (UN)", "📦 Outros ou diversos"),
    ("81 - dose tequila ouro (UN)", "📦 Outros ou diversos"),
    ("82 - dose tequila prata (UN)", "📦 Outros ou diversos"),
    ("83 - dose vodka absolut (UN)", "🥤 Bebidas"),
    ("84 - dose vodka ciroc (UN)", "🥤 Bebidas"),
    ("85 - dose vodka smirnoff (UN)", "🥤 Bebidas"),
    ("86 - dose whisky 12 anos (UN)", "🥤 Bebidas"),
    ("87 - dose whisky 8 anos (UN)", "🥤 Bebidas"),
    ("193 - fruta limao taiti (KG)", "📦 Outros ou diversos"),
    ("195 - polpa  morango  (KG)", "🥦 Hortifrúti"),
    ("196 - polpa  maracuja (KG)", "📦 Outros ou diversos"),
    ("197 - fruta kiwi (KG)", "🥦 Hortifrúti"),
    ("198 - polpa abacaxi (KG)", "🥦 Hortifrúti"),
    ("199 - fruta laranja  (KG)", "🥦 Hortifrúti"),
    ("200 - fruta limao siciliano (KG)", "📦 Outros ou diversos"),
    ("201 - anis estrelado  (KG)", "📦 Outros ou diversos"),
    ("202 - pimenta zinbro (KG)", "🧂 Temperos e Condimentos"),
    ("203 - pimenta rosa (KG)", "🧂 Temperos e Condimentos"),
    ("204 - hibisco  (KG)", "📦 Outros ou diversos"),
    ("205 - gelo cubo 5 kg (KG)", "📦 Outros ou diversos"),
    ("206 - gelo escama (KG)", "📦 Outros ou diversos"),
    ("207 - açucar refinado (branco) (KG)", "📦 Outros ou diversos"),
    ("208 - gengibre (KG)", "📦 Outros ou diversos"),
    ("209 - açucar organico (KG)", "📦 Outros ou diversos"),
    ("210 - clara de ovo pastelrizada (LT)", "🍞 Padaria e Massas"),
    ("211 - capsula de gas co2 (UN)", "📦 Outros ou diversos"),
    ("212 - agua c/gas 1.5 ltros (UN)", "🥤 Bebidas"),
    ("213 - espumante salton brut (UN)", "🧂 Temperos e Condimentos"),
    ("214 - canudo bio  (UN)", "🍽️ Descartáveis e utensílios"),
    ("379 - garrafa cointreau (UN)", "📦 Outros ou diversos"),
    ("381 - garrafa steinhaeguer (UN)", "📦 Outros ou diversos"),
    ("383 - garrafa sake  (UN)", "🥤 Bebidas"),
    ("384 - agua tonica 1.5 l (UN)", "🥤 Bebidas"),
    ("386 -  hisbisco (KG)", "📦 Outros ou diversos"),
    ("387 - agua s/gas 20 litros (LT)", "🥤 Bebidas"),
    ("388 - xarope de gengibre (LT)", "📦 Outros ou diversos"),
    ("389 - espuma moscow mule (LT)", "📦 Outros ou diversos"),
    ("393 - polpa abacaxi com hortela (KG)", "🥦 Hortifrúti"),
    ("398 - xarope de cramberry (UN)", "📦 Outros ou diversos"),
    ("399 - xarope de franboesa (UN)", "📦 Outros ou diversos"),
    ("400 - xarope de roma (UN)", "📦 Outros ou diversos"),
    ("401 - xarope de cha verde (UN)", "📦 Outros ou diversos"),
    ("402 - xarope de cha preto (UN)", "📦 Outros ou diversos"),
    ("561 - garrfa de martine dry (UN)", "📦 Outros ou diversos"),
    ("565 - fruta acerola (KG)", "📦 Outros ou diversos"),
    ("566 - polpa mirtilho (KG)", "📦 Outros ou diversos"),
    ("567 - canudo mexedor (UN)", "🍽️ Descartáveis e utensílios"),
    ("611 - xarope mix pessego e maracuja (ML)", "📦 Outros ou diversos"),
    ("640 -  ovo  pastelrizada (LT)", "🍞 Padaria e Massas"),
    ("656 - xarope de frutas vermelhas (LT)", "📦 Outros ou diversos"),
    ("661 - açucar sache (KG)", "📦 Outros ou diversos"),
    ("683 - fruta laranja bahia (KG)", "🥦 Hortifrúti"),
    ("686 - fruta maracuja   (KG)", "📦 Outros ou diversos"),
    ("688 - copo vidro (UN)", "🍽️ Descartáveis e utensílios"),
    ("696 - açucar  confeitero (KG)", "📦 Outros ou diversos"),
    ("710 - VASILHAME 20 LITROS (LT)", "📦 Outros ou diversos"),
    ("715 - suco manguary maracuja (UN)", "🥤 Bebidas"),
    ("721 - xarope cha verde (UN)", "📦 Outros ou diversos"),
    ("722 - xarope cranberry (UN)", "📦 Outros ou diversos"),
    ("723 - xarope  framboesa (UN)", "📦 Outros ou diversos"),
    ("726 - champanheira branca (UN)", "🍽️ Descartáveis e utensílios"),
    ("727 - saca rolha  (UN)", "🍽️ Descartáveis e utensílios"),
    ("742 - licor creme cassis (UN)", "🧀 Laticínios e Frios"),
    ("790 - polpa amora (KG)", "📦 Outros ou diversos"),
    ("830 - emustab (KG)", "📦 Outros ou diversos"),
    ("844 - canudo bio mexedor (UN)", "🍽️ Descartáveis e utensílios"),
    ("867 - espumante salton demi sec (UN)", "🧂 Temperos e Condimentos"),
    ("920 - xarope maçã verde (UN)", "📦 Outros ou diversos"),
    ("925 - adoçante sache (KG)", "📦 Outros ou diversos"),
    ("926 - adoçante  (KG)", "📦 Outros ou diversos"),
    ("100 - suco del valle uva (UN)", "🥦 Hortifrúti"),
    ("101 - suco del valle pessego (UN)", "🥤 Bebidas"),
    ("828 - agua sanitaria (UN)", "🥤 Bebidas"),
    ("834 - luva latex (UN)", "🥦 Hortifrúti"),
    ("846 - alcool 70% (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("853 - esfregao (UN)", "📦 Outros ou diversos"),
    ("864 - esponja lava louça (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("865 - bombril (UN)", "📦 Outros ou diversos"),
    ("903 - touca descartavel  (UN)", "📦 Outros ou diversos"),
    ("905 - faca descartavel  (UN)", "🍽️ Descartáveis e utensílios"),
    ("906 - colher descartavel (UN)", "🍽️ Descartáveis e utensílios"),
    ("907 - garfo descartavel  (UN)", "🍽️ Descartáveis e utensílios"),
    ("927 - lustra moveis (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("932 - desincrustante (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("934 - plastico filme (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("935 - esponja lava louça (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("181 - cigarro marlboro  (UN)", "📦 Outros ou diversos"),
    ("182 - cigarro dunhill (UN)", "📦 Outros ou diversos"),
    ("274 - queijo parmessao  (KG)", "🧀 Laticínios e Frios"),
    ("277 - queijo gorgonzola (KG)", "🧀 Laticínios e Frios"),
    ("278 - queijo brie (KG)", "🧀 Laticínios e Frios"),
    ("280 - cheddar (KG)", "📦 Outros ou diversos"),
    ("281 - cream cheese (KG)", "📦 Outros ou diversos"),
    ("283 - creme de leite  (KG)", "🧀 Laticínios e Frios"),
    ("284 - leite (LT)", "🧀 Laticínios e Frios"),
    ("298 -  file mignon (KG)", "🥩 Proteínas"),
    ("299 - entrecot (KG)", "📦 Outros ou diversos"),
    ("300 - coxa sobre coxa de frango (KG)", "🥩 Proteínas"),
    ("301 - peito de frango (KG)", "🥩 Proteínas"),
    ("303 - miolo da alcatra (KG)", "🥩 Proteínas"),
    ("304 - costela bovina  (KG)", "🥩 Proteínas"),
    ("309 - carne seca (KG)", "🥩 Proteínas"),
    ("310 - bacon (KG)", "🥩 Proteínas"),
    ("311 - linguiça calabresa (KG)", "🥩 Proteínas"),
    ("312 - linguiça paio (KG)", "🥩 Proteínas"),
    ("313 - frango passarinho (KG)", "🥩 Proteínas"),
    ("314 - picanha suina (KG)", "🥩 Proteínas"),
    ("316 - costela suina (KG)", "🥩 Proteínas"),
    ("450 - sal marinho fino  (KG)", "🧂 Temperos e Condimentos"),
    ("451 - sal marinho grosso (KG)", "🧂 Temperos e Condimentos"),
    ("452 - pimenta do reino (KG)", "🧂 Temperos e Condimentos"),
    ("457 - cravo da india  (KG)", "📦 Outros ou diversos"),
    ("459 - canela em po (KG)", "🧂 Temperos e Condimentos"),
    ("460 - canela em pau (inteira) (KG)", "🧂 Temperos e Condimentos"),
    ("466 - açafrao da terra (KG)", "📦 Outros ou diversos"),
    ("467 - hondashi (KG)", "📦 Outros ou diversos"),
    ("478 - mandioca aipim (KG)", "🥦 Hortifrúti"),
    ("487 - feijao preto (KG)", "🥫 Grãos e Secos"),
    ("503 - cogumelos paris (KG)", "📦 Outros ou diversos"),
    ("504 - cogumelos funghi seco (KG)", "📦 Outros ou diversos"),
    ("559 - caldo de galinha (KG)", "📦 Outros ou diversos"),
    ("593 - pimenta do reino grao (KG)", "🥫 Grãos e Secos"),
    ("625 - panceta suina (KG)", "🥩 Proteínas"),
    ("636 - queijo gouda (KG)", "🧀 Laticínios e Frios"),
    ("655 - paleta musculo bovino (KG)", "🥩 Proteínas"),
    ("699 - queijo ricota (KG)", "🧀 Laticínios e Frios"),
    ("701 - coxao duro (KG)", "🥩 Proteínas"),
    ("741 - sal refinado 1g (KG)", "🧂 Temperos e Condimentos"),
    ("818 - sal cebola/salsa (KG)", "🥦 Hortifrúti"),
    ("908 - peito de frango defumado (KG)", "🥩 Proteínas"),
    ("275 - queijo provolone (KG)", "🧀 Laticínios e Frios"),
    ("368 - file de peixe linguado (KG)", "🥩 Proteínas"),
    ("370 - file tilapia (KG)", "🥩 Proteínas"),
    ("373 - bacalhau (KG)", "📦 Outros ou diversos"),
    ("374 - pirarucu (KG)", "📦 Outros ou diversos"),
    ("375 - banda tambaqui (KG)", "📦 Outros ou diversos"),
    ("376 - costelinha de tambaqui (KG)", "🥩 Proteínas"),
    ("377 - salmao (KG)", "🧂 Temperos e Condimentos"),
    ("403 - azeite de dende (ML)", "🧂 Temperos e Condimentos"),
    ("404 - azeite de oliva (ML)", "🧂 Temperos e Condimentos"),
    ("405 - amido de milho (KG)", "📦 Outros ou diversos"),
    ("406 - tomate seco (KG)", "🥦 Hortifrúti"),
    ("407 - azeitona preta (KG)", "📦 Outros ou diversos"),
    ("408 - azeitona verde (KG)", "📦 Outros ou diversos"),
    ("409 - ovo de codorna (KG)", "📦 Outros ou diversos"),
    ("410 - vinagre aceto balsamico (ML)", "🧂 Temperos e Condimentos"),
    ("411 - shoyo (ML)", "🧂 Temperos e Condimentos"),
    ("412 - oleo de soja (ML)", "🥫 Grãos e Secos"),
    ("415 - leite de coco (ML)", "🧀 Laticínios e Frios"),
    ("416 - leite de condensado (ML)", "🧀 Laticínios e Frios"),
    ("417 - arroz parboilizado (KG)", "🥫 Grãos e Secos"),
    ("418 - arroz branco (KG)", "🥫 Grãos e Secos"),
    ("419 - arroz arboreo (KG)", "🥫 Grãos e Secos"),
    ("420 - massa espaguete (KG)", "🍞 Padaria e Massas"),
    ("421 - massa pene (KG)", "🍞 Padaria e Massas"),
    ("422 - massa linguine (KG)", "🍞 Padaria e Massas"),
    ("423 - massa nhoque (KG)", "🍞 Padaria e Massas"),
    ("424 - massa pastel  (KG)", "🍞 Padaria e Massas"),
    ("425 - massa ravioli (KG)", "🍞 Padaria e Massas"),
    ("426 - castanha para (KG)", "🥫 Grãos e Secos"),
    ("427 - castanha de caju  (KG)", "🥫 Grãos e Secos"),
    ("428 - mostarda  em graos (KG)", "🥫 Grãos e Secos"),
    ("429 - nozes  (KG)", "🥫 Grãos e Secos"),
    ("430 - damasco (KG)", "🥫 Grãos e Secos"),
    ("431 - fruta mirtilo (KG)", "📦 Outros ou diversos"),
    ("432 - fruta amora (KG)", "📦 Outros ou diversos"),
    ("434 - fruta framboesa (KG)", "📦 Outros ou diversos"),
    ("435 - vinagre maça (ML)", "🧂 Temperos e Condimentos"),
    ("436 - vinagre de alcool branco (ML)", "🧂 Temperos e Condimentos"),
    ("437 - catchup (KG)", "📦 Outros ou diversos"),
    ("438 - maionese (KG)", "🧂 Temperos e Condimentos"),
    ("439 - molho ingles (KG)", "🧂 Temperos e Condimentos"),
    ("440 - mel com favo (KG)", "📦 Outros ou diversos"),
    ("441 - alcaparras (KG)", "📦 Outros ou diversos"),
    ("442 - farinha de trigo  (KG)", "🥫 Grãos e Secos"),
    ("444 - farinha de panko (KG)", "🥫 Grãos e Secos"),
    ("445 - farinha de mandioca (KG)", "🥦 Hortifrúti"),
    ("446 - vinho tinto garrafao (ML)", "🥤 Bebidas"),
    ("447 - vinho branco garrafao (ML)", "🥤 Bebidas"),
    ("448 - garrafa conhaque (ML)", "🥤 Bebidas"),
    ("462 - ajinomoto (KG)", "🧂 Temperos e Condimentos"),
    ("465 - açucar demerara (KG)", "📦 Outros ou diversos"),
    ("470 - massa fettutine (KG)", "🍞 Padaria e Massas"),
    ("475 - vinagre de arroz (ML)", "🥫 Grãos e Secos"),
    ("491 - amendoas laminadas (KG)", "🥫 Grãos e Secos"),
    ("497 - fuba de milho (KG)", "🥫 Grãos e Secos"),
    ("508 - FAROFA (KG)", "📦 Outros ou diversos"),
    ("531 - pao de alho (KG)", "🥦 Hortifrúti"),
    ("532 - salada pratos (KG)", "🧂 Temperos e Condimentos"),
    ("533 - batata soute (KG)", "🥦 Hortifrúti"),
    ("587 - chimichurry  (KG)", "🧂 Temperos e Condimentos"),
    ("588 - cominho em po (KG)", "📦 Outros ou diversos"),
    ("591 - noz moscada (KG)", "📦 Outros ou diversos"),
    ("592 - pimenta do reino branca (KG)", "🧂 Temperos e Condimentos"),
    ("594 - file de pescada cambucu (KG)", "🥩 Proteínas"),
    ("596 - mostarda dijon (UN)", "🧂 Temperos e Condimentos"),
    ("598 - salsao (UN)", "🥦 Hortifrúti"),
    ("600 - batata lavada  (KG)", "🥦 Hortifrúti"),
    ("648 - fruta ameixa  (KG)", "🥦 Hortifrúti"),
    ("658 - jantar  (UN)", "❄️ Congelados e Pré-prontos"),
    ("663 - polvo (KG)", "🥩 Proteínas"),
    ("672 - alho em po  a granel (KG)", "🥦 Hortifrúti"),
    ("673 - cajun picante em po granel (KG)", "📦 Outros ou diversos"),
    ("674 - cebola em po a granel (KG)", "🥦 Hortifrúti"),
    ("676 - coentro em po a granel  (KG)", "🧂 Temperos e Condimentos"),
    ("677 - lemon pepper em po a granel (KG)", "🧂 Temperos e Condimentos"),
    ("678 - fumaça em po a granel  (KG)", "🧂 Temperos e Condimentos"),
    ("679 - manjerona em po a granel  (KG)", "📦 Outros ou diversos"),
    ("680 - salsa em po a granel  (KG)", "🧂 Temperos e Condimentos"),
    ("681 - salvia em po a granel  (KG)", "🧂 Temperos e Condimentos"),
    ("685 - lombo suino (KG)", "🥩 Proteínas"),
    ("689 - file  dourado (KG)", "🥩 Proteínas"),
    ("698 - catchup  (UN)", "📦 Outros ou diversos"),
    ("706 - gema de ovo pasteurizada (UN)", "📦 Outros ou diversos"),
    ("717 - file de costela porc ancho (KG)", "🥩 Proteínas"),
    ("748 - mel  fracionado (cafe) (UN)", "📦 Outros ou diversos"),
    ("776 - file mignon suino (KG)", "🥩 Proteínas"),
    ("782 - castanha do brasil media (KG)", "🥫 Grãos e Secos"),
    ("785 - massa papardeli (KG)", "🍞 Padaria e Massas"),
    ("788 - massa caseira (KG)", "🍞 Padaria e Massas"),
    ("815 - tainha fresca (KG)", "📦 Outros ou diversos"),
    ("829 - acen bovino (KG)", "🥩 Proteínas"),
    ("833 - flor comestivel  (UN)", "🥦 Hortifrúti"),
    ("835 - broto alface crespa  (UN)", "🥦 Hortifrúti"),
    ("836 - broto alface mimosa (UN)", "🥦 Hortifrúti"),
    ("837 - broto alface lisa (UN)", "🥦 Hortifrúti"),
    ("838 - broto cenoura (UN)", "🥦 Hortifrúti"),
    ("839 - broto agriaõ  (UN)", "🥦 Hortifrúti"),
    ("840 - broto beterraba (UN)", "🥦 Hortifrúti"),
    ("841 - broto coentro (UN)", "🥦 Hortifrúti"),
    ("842 - broto mostarda (UN)", "🥦 Hortifrúti"),
    ("845 - brocolis comun (UN)", "🥦 Hortifrúti"),
    ("847 - broto rabanete (UN)", "🥦 Hortifrúti"),
    ("848 - broto rucula  (UN)", "🥦 Hortifrúti"),
    ("849 - broto amaranto (UN)", "🥦 Hortifrúti"),
    ("852 - arroz integral  (KG)", "🥫 Grãos e Secos"),
    ("855 - file saithe bacalhau (KG)", "🥩 Proteínas"),
    ("860 - massa lasanha/canelone (KG)", "🍞 Padaria e Massas"),
    ("866 - broto repolho (UN)", "🥦 Hortifrúti"),
    ("869 - broto couve roxa (UN)", "🥦 Hortifrúti"),
    ("896 - broto alface roxa (UN)", "🥦 Hortifrúti"),
    ("897 - amaciante de carne  (KG)", "🥩 Proteínas"),
    ("917 - alho em flocos (KG)", "🥦 Hortifrúti"),
    ("921 - mostarda  (UN)", "🧂 Temperos e Condimentos"),
    ("937 - pitaia (KG)", "🥦 Hortifrúti"),
    ("472 - cafe tradicional (KG)", "📦 Outros ou diversos"),
    ("536 - polvilho azedo (KG)", "🥫 Grãos e Secos"),
    ("550 - manteiga fracionada (sache-cafe) (UN)", "🧀 Laticínios e Frios"),
    ("552 - queijo coalho (KG)", "🧀 Laticínios e Frios"),
    ("560 - adoçante  (LT)", "📦 Outros ou diversos"),
    ("582 - cream cheese fracionado (cafe) (UN)", "📦 Outros ou diversos"),
    ("583 - geleias frecionadas (cafe) (UN)", "🍬 Doces e Sobremesas"),
    ("589 - gergelim branco  (KG)", "📦 Outros ou diversos"),
    ("590 - gergelim preto (KG)", "📦 Outros ou diversos"),
    ("605 - fruta abacaxi  (KG)", "🥦 Hortifrúti"),
    ("609 - uva rubi (KG)", "🥦 Hortifrúti"),
    ("616 - cha camomila (UN)", "📦 Outros ou diversos"),
    ("617 - cha hortela (UN)", "🥦 Hortifrúti"),
    ("628 - uva passa preta (KG)", "🥦 Hortifrúti"),
    ("634 - povilho azedo  (KG)", "🥫 Grãos e Secos"),
    ("654 - queijo mussarela fatiado (KG)", "🧀 Laticínios e Frios"),
    ("665 - aroma artificial baunilha (ML)", "📦 Outros ou diversos"),
    ("666 - chantily 1L (KG)", "🧀 Laticínios e Frios"),
    ("667 - chocolate barra ao leite (KG)", "🧀 Laticínios e Frios"),
    ("668 - chocolate em pó 50% (KG)", "🍬 Doces e Sobremesas"),
    ("669 - chocolate granulado (KG)", "🍬 Doces e Sobremesas"),
    ("670 - coco ralado  (KG)", "📦 Outros ou diversos"),
    ("671 - doce de leite  (KG)", "🧀 Laticínios e Frios"),
    ("675 - cha erva doce a granel (KG)", "🍬 Doces e Sobremesas"),
    ("694 - uva italia (KG)", "🥦 Hortifrúti"),
    ("702 - chocolate barra branco  (KG)", "🍬 Doces e Sobremesas"),
    ("708 - salsicha congelada (KG)", "🥩 Proteínas"),
    ("709 - mortadela fatiada (KG)", "🧀 Laticínios e Frios"),
    ("712 - mexedor   para cafe (UN)", "🍽️ Descartáveis e utensílios"),
    ("718 - fruta figo (UN)", "🥦 Hortifrúti"),
    ("743 - mini croissant chocolate (KG)", "🍞 Padaria e Massas"),
    ("744 - mini croissant frango/requeijao (KG)", "🥩 Proteínas"),
    ("747 - mistura de bolo (UN)", "🍬 Doces e Sobremesas"),
    ("751 - mini croissant s/recheio (KG)", "🍞 Padaria e Massas"),
    ("753 - chia semente (UN)", "🥫 Grãos e Secos"),
    ("760 - mini croissant  goiabada (KG)", "🍞 Padaria e Massas"),
    ("761 - mini couvert (KG)", "🥦 Hortifrúti"),
    ("768 - cha cidreira (UN)", "📦 Outros ou diversos"),
    ("769 - cha frutas vermelhas (UN)", "📦 Outros ou diversos"),
    ("770 - mini coxinha de frango (KG)", "🥩 Proteínas"),
    ("771 - mini bolinha de queijo (KG)", "🧀 Laticínios e Frios"),
    ("819 - aroma baunilha (UN)", "📦 Outros ou diversos"),
    ("831 - pao sete graos (UN)", "🥫 Grãos e Secos"),
    ("916 - nectarina (KG)", "🥦 Hortifrúti"),
    ("930 - chocolate sonho de valsa (KG)", "🍬 Doces e Sobremesas"),
    ("939 - cha alecrim (UN)", "🥦 Hortifrúti"),
    ("276 - queijo mussarela  peça (KG)", "🧀 Laticínios e Frios"),
    ("515 - molho tomate  (KG)", "🥦 Hortifrúti"),
    ("517 - demmi glass (KG)", "📦 Outros ou diversos"),
    ("518 - molho bechamel (KG)", "🧂 Temperos e Condimentos"),
    ("519 - caldo legumes  (LT)", "📦 Outros ou diversos"),
    ("522 - oleo de carvao (LT)", "📦 Outros ou diversos"),
    ("528 - burrata (UN)", "🧀 Laticínios e Frios"),
    ("535 - bicarbonato de sodio (KG)", "📦 Outros ou diversos"),
    ("537 - coca cola litros (UN)", "🥤 Bebidas"),
    ("547 - fruta morango natural (KG)", "🥦 Hortifrúti"),
    ("548 - molho roti madeira (KG)", "🧂 Temperos e Condimentos"),
    ("551 - linguiça bock  (KG)", "🥩 Proteínas"),
    ("554 - pao medieval (australiano) (KG)", "🍞 Padaria e Massas"),
    ("555 - pao mini brioche (KG)", "🍞 Padaria e Massas"),
    ("556 - peixe tamboriu (KG)", "🥩 Proteínas"),
    ("557 - mozzarela de bufala (bolinha cerejinha) (KG)", "🧀 Laticínios e Frios"),
    ("562 - coca cola  zero 2 litros (UN)", "🥤 Bebidas"),
    ("563 - guarana 2 litros (UN)", "🥤 Bebidas"),
    ("585 - charque (KG)", "🥩 Proteínas"),
    ("595 - grao de bico (KG)", "🥫 Grãos e Secos"),
    ("613 - fruta pera (KG)", "🥦 Hortifrúti"),
    ("614 - abobora comum (KG)", "🥦 Hortifrúti"),
    ("615 - linguiça blumenau (KG)", "🥩 Proteínas"),
    ("618 - gergelim em  pasta (UN)", "📦 Outros ou diversos"),
    ("626 - kit feijoada (KG)", "🥩 Proteínas"),
    ("629 - extrato de tomate (UN)", "🥦 Hortifrúti"),
    ("630 - molho de  salada lisa (UN)", "🧂 Temperos e Condimentos"),
    ("632 - suco de uva  1,5 (UN)", "🥦 Hortifrúti"),
    ("633 - suco de laranja  5 litros  (LT)", "🥦 Hortifrúti"),
    ("635 - molho tare (LT)", "🧂 Temperos e Condimentos"),
    ("638 - aipim ou mandioca (KG)", "🥦 Hortifrúti"),
    ("645 - pessego em caldas (UN)", "🍬 Doces e Sobremesas"),
    ("646 - sagu (KG)", "📦 Outros ou diversos"),
    ("649 - massa conchiglioni (CX)", "🍞 Padaria e Massas"),
    ("650 - tapioca granulada (KG)", "🥫 Grãos e Secos"),
    ("653 - CHANPIGNON (KG)", "📦 Outros ou diversos"),
    ("659 - arroz de sushi (KG)", "🥫 Grãos e Secos"),
    ("660 - massa talharin  (KG)", "🍞 Padaria e Massas"),
    ("684 - mozzarela de bufala  peça (KG)", "🧀 Laticínios e Frios"),
    ("700 - manguari concentrado (UN)", "📦 Outros ou diversos"),
    ("703 - mini risolis de carne (KG)", "🥩 Proteínas"),
    ("704 - mini salsicha empanada (KG)", "🥩 Proteínas"),
    ("705 - mini kibe com requeijao (KG)", "🥩 Proteínas"),
    ("713 - molho tabasco verde (UN)", "🧂 Temperos e Condimentos"),
    ("714 - molho tabasco vermelha (UN)", "🧂 Temperos e Condimentos"),
    ("716 - amendoin torrado  (UN)", "📦 Outros ou diversos"),
    ("719 - sache palito gental (UN)", "📦 Outros ou diversos"),
    ("746 - bobina plastica (UN)", "🧴 Produtos de Limpeza e Higiene"),
    ("754 - farinha de arroz (UN)", "🥫 Grãos e Secos"),
    ("759 - quiabo (KG)", "📦 Outros ou diversos"),
    ("762 - espinafre (UN)", "🥦 Hortifrúti"),
    ("763 - ervilha (KG)", "🥫 Grãos e Secos"),
    ("764 - abacaxi desidratado (KG)", "🥦 Hortifrúti"),
    ("765 - laranja desidratada (KG)", "🥦 Hortifrúti"),
    ("766 - limao desidratado (KG)", "📦 Outros ou diversos"),
    ("767 - oregano (KG)", "📦 Outros ou diversos"),
    ("856 - agar agar (UN)", "📦 Outros ou diversos"),
    ("857 - flocos de arroz (KG)", "🥫 Grãos e Secos"),
    ("858 - gelatina em po (KG)", "📦 Outros ou diversos"),
    ("862 - pistache granel  (KG)", "📦 Outros ou diversos"),
    ("863 - chia granel (KG)", "🥫 Grãos e Secos"),
    ("883 - file de pescada(mistura)(KG)", "🥩 Proteínas"),
    ("900 - copo long drink (UN)", "🍽️ Descartáveis e utensílios"),
    ("902 - copo cerveja (UN)", "🥤 Bebidas"),
    ("915 - pessego amarelo (UN)", "📦 Outros ou diversos"),
    ("918 - molho pimenta vermelha (UN)", "🧂 Temperos e Condimentos"),
    ("924 - dianteiro bovino (KG)", "🥩 Proteínas"),
    ("928 - taca decanter (UN)", "📦 Outros ou diversos"),
    ("936 -  polenta pacote (KG)", "📦 Outros ou diversos"),
    ("938 - taca vidro (UN)", "📦 Outros ou diversos"),
    ("000 - Chopp (Litros)", "🥤 Bebidas"),
]
